services:
  builder:
    build:
      context: ..
      dockerfile: .buildkite/Dockerfile
    volumes:
      - ../:/src
      - /var/lib/buildkite-agent/.gem/credentials:/home/buildkite-agent/.gem/credentials
